### ISSUE TITLE
//air change

### ISSUE THREAD

**Issue by HyperBeast43** [IntellectualSites/FastAsyncWorldEdit#1065]
### What feature do you want to see added?

change the //air command to do "//replace !air air" instead of "//set air"

### Are there any alternatives?

.

### Anything else?

this would reduce the number of attempted block changes, as it won't try to change air into air

**Comment by SirYwell** [comment]
That's not how FAWE works. A mask means, that FAWE needs to read every block from the world, while just setting the blocks means it doesn't need to read the blocks but only write them.

**Comment by MattBDev** [comment]
This would slow down the `//air` command because it would require the plugin to perform an extra step before setting blocks.
Think of it this way, right now you can run `//air` and it just changes every single block regardless of what it is. Your proposal would mean that for every single block the plugin would ask the game "Is this block air?" and wait for the response back. In large edits this can lead to a significant slowdown.
