### ISSUE TITLE
FAWE removes things randomly OUTSIDE of the selection.

### ISSUE THREAD

**Issue by toxicsnails** [IntellectualSites/FastAsyncWorldEdit#1169]
### Server Implementation

Paper

### Server Version

1.17.+

### Describe the bug

If you make a selection, FAWE will occasionally delete some of a build that is outside of said selection. It's happened several times, on 1.17 Build 28 _and_ 1.17 build 42. 

![2021-07-06_18 48 30](https://user-images.githubusercontent.com/86858026/124650042-2d813a00-de91-11eb-81b5-009d7c4ccefc.png)
The selection was between the two spruce leaves, but FAWE decided it was going to delete the entirety of the oak bridge in the picture for no reason. (The player had already rebuilt the bridge when this screenshot was taken).

It also happened a few days ago where it deleted some of my own progress when I //set air nearby to it but had not actually selected the area it deleted.

### To Reproduce

1. Have 1.17 build 42 installed on Paper
2. Build something (bridge, scenery, tree, etc)
3. Select an area nearby to the build and do a command (we've been doing //set 0)
4. It deletes the build nearby.

### Expected behaviour

We just expected it to apply the changes to the selected area, not delete outside of the area.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/596d3d96eff1429586862b9b0bf9d009

### Fawe Version

1.17 Build 42

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit-1.17/ and the issue still persists.

**Comment by BuggyAl** [comment]
im not sure if this is related but making a selecting and using //caves can modify outside selection

**Comment by LaurenceBarnes** [comment]
> im not sure if this is related but making a selecting and using //caves can modify outside selection

I also encounter this issue, starting with my update from FAWE-1.16-726 to FAWE-1.16-735. it appears to happen even on the FAWE-1.17 build. I did not ever use //caves, however there's a possibility it interferes with other commands for some reason if it works as you said

**Comment by dordsor21** [comment]
Try with the latest FAWE build.

**Comment by Combustible** [comment]
We have been experiencing this too. I think it's not so much that the FAWE operation effects outside the bounds, but it seems to periodically just roll back chunk sections. to what they were before. This was definitely still a problem as recently as build 81. We've just upgraded to the most recent version (build 97) and will post again here if we encounter this again.

**Comment by LaurenceBarnes** [comment]
yes, it did affect all recently (by hand changed) chunks FAWE was operating in, but outside the selected areas

**Comment by Tobberz** [comment]
We also have been experiencing exactly the same issues outlined above, if it helps. This appears to be widespread.

**Comment by LaurenceBarnes** [comment]
> We also have been experiencing exactly the same issues outlined above, if it helps. This appears to be widespread.

did you test the newest builds?

**Comment by Aurelien30000** [comment]
Unfortunately, issue persists, a player has been able to replicate the issue :/ Here are some details ;)

# Debug:
https://athion.net/ISPaster/paste/view/b181fea257dd490ba4acf0b7d7942c2f

# Screenshots:

_Before (selection is circled with particles)_
![image](https://user-images.githubusercontent.com/43724816/127529473-cfe84203-c708-4e5c-b217-570829afa36c.png)
 
_After (selection is circled with particles)_
![image](https://media.discordapp.net/attachments/447343669788278784/870291297540399184/2021-07-29_15.05.40.png)

_Chunk grid (seems unrelated though)_
![image](https://user-images.githubusercontent.com/43724816/127529660-c3517d51-e31d-4256-9dca-8cb64e27af1d.png)

**Comment by LaurenceBarnes** [comment]
chunk grid is related, I have confirmed that before

**Comment by toxicsnails** [comment]
It’s still doing it on the newest build that I installed last night. It just occurred to one of my players, exact same as before

**Comment by Combustible** [comment]
Still present in 1.17-97;e1d18dc

**Comment by Aurelien30000** [comment]
## Again on build 1.17-111 :/

Player ``//set calcite`` the ceiling.

---

_Before:_
![image](https://user-images.githubusercontent.com/43724816/128538924-65012c7b-4455-44c7-860b-39a474a5b0f0.png)

_After:_
![image](https://user-images.githubusercontent.com/43724816/128538974-86ba43c1-d523-4c9d-a272-65cfa8c37d9d.png)

**Comment by Combustible** [comment]
We continue to have this pop up and I think have learned a little bit more about this behavior. 

Our current theory is: 

- Something happens that causes FAWE to create an internal cached copy of one or more chunk sections, that is no longer coupled to the actual world
- You can then change those chunk sections by hand, and it works fine on the server/client, but doesn't update this FAWE cached copy
- You can run /save-all, and everything still looks fine server/client wise
- When you //copy that area, you will copy the cache'd version that FAWE has, not what's actually there in the world
- When you select a block in that chunk section and //set it, FAWE will pull the cached chunk section instead of what's actually in the world, and roll back the entire chunk section to the incorrect cached copy, plus the //set.
- Once you do this and the rollback happens, this has a high chance of synchronizing the world and FAWE again, and things work normally after. You can manually edit, //copy, etc. and it works as expected. Sometimes it continues to be decoupled though, and further changes will again cause rollbacks.

Still unknown what causes entering this strange state to begin with.

Initially I was thinking maybe FAWE isn't saving the data to the world, and maybe it's just sending updated chunks to the client... but I don't know. A new player who shows up, never having seen that area before (i.e. me, showing up to see someone demonstrate this problem) will see the new/correctly updated area. But then the person demonstrated //copying an area, and what was pasted was not what I saw the source was (split differently along chunk section boundaries). So I think FAWE is hanging onto some world data that has maybe been disassociated from the actual world?

**Comment by dordsor21** [comment]
Please see if the latest build might have fixed this

**Comment by dordsor21** [comment]
:eyes:

**Comment by Aurelien30000** [comment]
My players are trying to reproduce the issue, I'll let you know. _Atm it seems fixed_

**Comment by tmkonermx** [comment]
Still preset on FastAsyncWorldEdit-Bukkit-1.17-139
Paper-783 1.16.5
Selection is what I have //set 0 then //undo
![image](https://user-images.githubusercontent.com/89164256/129971303-bee1c7d9-03ba-403e-8932-9166df49a3bd.png)

I don't know if it is related but when this bug appear I have this in console:
[22:05:26 INFO]: Using com.fastasyncworldedit.bukkit.adapter.NMSRelighterFactory as relighter factory.

This info shows rarely but I experience slightly laggy behavior when this happen

**Comment by dordsor21** [comment]
Outdated FAWE build, that's clearly an informative message saying that lighting is being done, not actually describing that the issue happened...

**Comment by dordsor21** [comment]
Seems fixed.

**Comment by Combustible** [comment]
I believe the problem mentioned above by @tmkonermx is actually the new bug #1237, which also narrows down the version it was introduced even further. Note that in this case the chunk area seems to have been removed/corrupted, not rolled back (which is what this bug 1169 was about)
