### ISSUE TITLE
Invalid pattern replacement

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncWorldEdit#1532]
Currently testing on build 63, `//replace ##logs air` throws
![](https://i.imgur.com/zcvQp3G.png)

Maybe some correlation with `https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/1509` ?

**Comment by IIIagoC** [comment]
**This pattern is hell useful and sometimes irreplaceable!!**
 
On 1.12 we had other alternatives since typing "78" would recognize all snow blocks. But, on 1.17, the only way to recognize all snow blocks on a command is writing the ID one by one, without tab complete. 

For comparison reasons, here two commands that do the exact same thing, but in different versions: 
**1.12 command:** `//replace 35 0`
**1.17 corrected:** `//replace ##wool 0`
**1.17 atm:** `//replace 35:0,35:1,35:2,35:3,35:4,35:5,35:6,35:7,35:8,35:9,35:10,35:11,35:12,35:13,35:14,35:15 0`


The situation gets even harder when some type of blocks dont have ANY numberID on 1.12 or 1.17:
(e.g. Walls)
**How should work:** `//replace ##walls 0` 
**Only way it works:** `//replace cobblestone_wall,mossy_cobblestone_wall,brick_wall,prismarine_wall,red_sandstone_wall, mossy_stone_brick_wall,granite_wall,stone_brick_wall,nether_brick_wall,andesite_wall,red_nether_brick_wall,sandstone_wall, end_stone_brick_wall,diorite_wall,blackstone_wall,polished_blackstone_brick_wall,polished_blackstone_wall, cobbled_deepslate_wall,polished_deepslate_wall,deepslate_tile_wall,deepslate_brick_wall,mud_brick_wall‌ 0`

Please give it some special attention, even though i'm not part of you guys to ask for such thing
