### ISSUE TITLE
Schematics cannot be deleted without specifying the extension

### ISSUE THREAD

**Issue by TheoRetisch1** [IntellectualSites/FastAsyncWorldEdit#1797]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Schematics cannot be deleted without specifying the extension. If no extension is given, the schematic to be deleted cannot be found. Since there are schematics ending in `.schem` as well as schematics ending in `.schematic`, specifying the extension is confusing and very inconvenient to use. It would be great if specifying the schematic name would be enough to delete it.

### To Reproduce

1. Create a schematic (`//copy` + `//schem save test`)
2. Delete the schematic` /schem delete test` -> the schematic cannot be found.
3. The schematic can only be found + deleted, if one specify the extension: `/schem delete test.schematic`

### Expected behaviour

The schematic should be deletable without specifying the extension .schem or .schematic.

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ca69266f035b4271a9c42c9acf26f108

### Fawe Version

 FastAsyncWorldEdit version 2.3.1-SNAPSHOT-199;a6b1b41

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
> Since there are schematics ending in .schem as well as schematics ending in .schematic

This is a prime example why specifying the file extension is so important.
Given the following scenario, a file called `a` is present in the formats `a.schem`, `a.schematic`, `a.nbt` and `a.structure`.
Attempting to delete a file in game, based on the name, would delete 4 files in this scenario, because the name is equal.
Such an implicit behavior goes against the standards of working with files.
