### ISSUE TITLE
Improvement of the "disallowed-blocks" function

### ISSUE THREAD

**Issue by NoltoxGit** [IntellectualSites/FastAsyncWorldEdit#1823]
### What feature do you want to see added?

Hello !

I have just found the "disallowed-blocks" function in the FAWE configuration. It's a pretty interesting option but something is missing to make it more functional, let me explain:

When you add a block in this category, you should not be able to do anything with WorldEdit (especially with the //stack, //copy and //paste commands).

### Are there any alternatives?

No alternative exist.

**Comment by dordsor21** [comment]
That's how it works unless you have bypass permissions

**Comment by almic** [comment]
Can we revisit this? The reasoning given by @dordsor21is incorrect, as that is not how disallowed-blocks works. You can use //stack, //copy, and //paste with disallowed blocks, in fact this has been opened as a bug and closed because that's "working as intended." I would also like to bring up that "universal-disallowed-blocks" seems to be ineffective, as it appears to be worded to say that "disallowed-blocks" will be applied to all edits, not just patterns, which is actually does not.

I am very confused by these two statements made, as you say it already works this way, while another says that it doesn't work that way and that's the intention, then saying to use that "universal" option which actually seems to do nothing.
