### ISSUE TITLE
Undo of big pastes does not remove all blocks

### ISSUE THREAD

**Issue by PapiCapi** [IntellectualSites/FastAsyncWorldEdit#1861]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

The //undo for big structures does not seem to remove all the blocks pasted.

### To Reproduce

1. Copy a big amount of blocks
2. Paste it somewhere ( for example in the sky or in the void )
3. Undo
4. You should see blocks flying around

### Expected behaviour

Clear all the blocks pasted.

### Screenshots / Videos

https://www.youtube.com/watch?v=POocbUssI9s

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/1245dfd6feb14454a9f6596869f929f3

### Fawe Version

FastAsyncWorldEdit version 2.4.1-SNAPSHOT-237;dbfb521

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

### Anything else?

Actually my build isn't the newest but the last two were updates of paperweight and some docs modifications as far as i see.

**Comment by PierreSchwang** [comment]
Is this just a visual bug, or are the blocks still present after a rejoin?

**Comment by PapiCapi** [comment]
They are still present after a rejoin

**Comment by NotMyFault** [comment]
What was the amount of blocks you did this with? With 150 billion blocks I had no issue

**Comment by PapiCapi** [comment]
I tried with ~3 millions. I can reproduce it really easily so it maybe comes from another plugin ?
Anyway, i got a schematic to send you if you want to test with it. I can't join it here

**Comment by anonyco** [comment]
Please send the schematic here in GitHub.

There should be a button at the bottom of this text box where you type the comment that says "Attach files by dragging & dropping, selecting or pasting them." If you are unable to find this button, then you can drag and drop the file onto this comment text box.

This doesn't feel like the sort of issue that would be caused by particular blocks (I would expect errors being thrown in the console instead of silence), but it's very worth trying out the schematic.

**Comment by PapiCapi** [comment]
[undoBug.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/9127976/undoBug.zip)
I could't add the simple .schem file so after zipping it, github seems to be okay with that file extension

**Comment by anonyco** [comment]
Ah. That makes sense. Many thanks for sending the schematic file. I am looking into it.

**Comment by PapiCapi** [comment]
So i just re-tried with only a few plugins ( FAWE, Multiverse-Core and PlotSquared ) and the bug is not showing at the first //undo.
I needed to paste and undo one more time for my bug to appear. 
I also tried to enable the debug output but nothing more in the console.

**Comment by CJBlakey** [comment]
I'm experiencing a similar issue, but with a relatively small paste (a gateway for a castle, maybe a thousand or so blocks tops)

**Comment by Folas1337** [comment]
Same has been happening here throughout several months by now, just thought I'd add my experience to this issue at least :)

It's just happened yesterday for a user with a massive schematic (like 300 million blocks) where after using "//undo" small fragments where left over seemingly at random.

**Comment by PierreSchwang** [comment]
> [undoBug.zip](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/9127976/undoBug.zip) I could't add the simple .schem file so after zipping it, github seems to be okay with that file extension

I'm able to replicate the issue using that schematic multiple times

**Comment by OneLiteFeather** [comment]
It doesn't happen when you do //paste without -e and then //undo. It always happens when you //paste -e and //undo (sometimes need to be done twice in a row) on these schematics, I guess it is an issue with entities, some TileEntities break as seen in my debugpaste here.

Debugpaste with log and stacktrace:
https://athion.net/ISPaster/paste/view/dc7b33a8f48d4ad0b46728aeb48f8fbe
Maybe this can be helpful for developers
