### ISSUE TITLE
FastAsyncWorldedit lagging the server for a permission check

### ISSUE THREAD

**Issue by LuluxClient** [IntellectualSites/FastAsyncWorldEdit#1917]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

For some weird reasons Fawe uses a lot of % when no one is using it: https://spark.lucko.me/FmPS683ntW
Currently 250 players online

### To Reproduce

1. Have 250 players online
2. do a spark

### Expected behaviour

Fawe shouldn't use that much when no one is using FAWE

### Screenshots / Videos

https://spark.lucko.me/FmPS683ntW

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/ee8816fd99b946f19511adb29b2b99e3

### Fawe Version

2.4.4 snapshot 265

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by SirYwell** [comment]
The permission checks come from WorldGuard (which uses (FA)WE for permissions), but I guess the actual issue is the expensive context calculation from ajLeaderboards. I don't think FAWE can do anything better here unless you can specify a permission check *caused* by FAWE that is happening too often.
