### ISSUE TITLE
Using //undo in a claim fails using inventory mode

### ISSUE THREAD

**Issue by CooperRules** [IntellectualSites/FastAsyncWorldEdit#2073]
### Server Implementation

Paper

### Server Version

1.19.2

### Describe the bug

When a user has a claim and they are trying to //undo or //redo one of their edits, the command fails. FAWE still sends the "Undid 1 available edits", but no action actually occurs. This error does NOT occur if the inventory mode of FAWE is set to 0 (creative mode), and only occurs on 1 and 2. 

No error in console.

### To Reproduce

1. Set inventory mode to 1 in config
2. Make an edit, stand in a claim, and attempt to undo it
3. Bug

### Expected behaviour

1. User makes an edit, wants to undo it
2. Uses //undo, gets "Undid 1 available edits", last edit is undone.

### Screenshots / Videos

https://www.youtube.com/watch?v=sjkk55my-_0

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/16c28ba3b97e4bb7a9d8b5cea2193377

### Fawe Version

FastAsyncWorldEdit version 2.5.1-SNAPSHOT-344;5e8bc5c

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by OneLiteFeather** [comment]
Can you tell me which plugin is used for claiming in your video? Is it Griefprevention?

**Comment by OneLiteFeather** [comment]
I looked into it a little bit more to find out if this issue is more on the side of Griefprevention. That plugin wasn't updated after 1.17, even the fork is 1 year untouched. I guess if you use a different protection plugin or the right version for the plugin (in this case 1.17 server and fawe) it might could work, but it's not a good idea to downgrade your minecraft server as it might break. Better to change the plugin or fork it and make the usage of fawe in Griefprevention working right again.
