### ISSUE TITLE
Illegal Argument Exception w/ Nova

### ISSUE THREAD

**Issue by GrimPlayzs** [IntellectualSites/FastAsyncWorldEdit#2261]
### Server Implementation

Spigot

### Server Version

1.19.4

### Describe the bug

When attempting to break blocks with any of the custom items added by Nova a Spigot Modding API causes a exception shown in chat and console.
![Screenshot 2023-06-03 213608](https://github.com/IntellectualSites/FastAsyncWorldEdit/assets/89351648/1739ccc5-4c66-4311-8104-2a5a56dc8a4d)

### To Reproduce

Download Nova and FAWE onto a Spigot server with the Machines addon.
Give yourself any of the custom tools
Break a block

### Expected behaviour

I expect no errors to be shown

### Error log (if applicable)

https://gist.github.com/GrimPlayzs/64f80b8b1c38f986c6f1f9a337ee4874

### Fawe Debugpaste

https://athion.net/ISPaster/paste/view/edeb6f1821624a148ae7668ab2c397a9

### Fawe Version

FastAsyncWorldEdit version 2.6.2-SNAPSHOT-448;048dcaf

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://ci.athion.net/job/FastAsyncWorldEdit/ and the issue still persists.

**Comment by NotMyFault** [comment]
Issues with third party plugin integrations should be reported to their author(s).

**Comment by ByteZ1337** [comment]
> Issues with third party plugin integrations should be reported to their author(s).

I don't really understand how you expect us to fix this since it's literally a hardcoded if-block:

https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/d7cc65d2f238467e9fc4539e8dbeb9ef448f3598/worldedit-bukkit/adapters/adapter-1_20/src/main/java/com/sk89q/worldedit/bukkit/adapter/ext/fawe/v1_20_R1/PaperweightAdapter.java#L919-L924

and we'd really like to avoid adding runtime patches for third party plugins.
