### ISSUE TITLE
Part of the chunk gets removed when using //set after a restart 

### ISSUE THREAD

**Issue by aurorasmiles** [IntellectualSites/FastAsyncWorldEdit#332]
# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

https://athion.net/ISPaster/paste/view/4378e617b28b40c2b68522870f357ac1

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

1.15 build 61 (latest as of testing this)

**[REQUIRED] Spigot/Paper Version Number:** 

Paper 1.15.2 build 89 (latest as of testing this)

**[REQUIRED] Description of the problem:**

After restarting the server, the first //set sometimes removes all blocks in the chunk over the selection
Pictures of the issue:
https://drop.cutiepie.at/cxy2542w0pk0a7
(The first selection (green) is in one chunk, the second is in the next)
https://drop.cutiepie.at/668cktfqcpuidkor

**How to replicate**:

1. Restart your server. Apparently this issue only works on the first //set after the restart
2. Select to blocks in different chunks
3. Use the //set command, for example //set 1

**Plugins being used on the server:**

None

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit-1.13/issues?utf8=%E2%9C%93&q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.14.4](https://ci.athion.net/job/FastAsyncWorldEdit-pipeline/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by stevekr3w** [comment]
Spigot 1.15.2 - FAWE build 130 - still an issue!

**Comment by MattBDev** [comment]
@stevekr3w We are well aware. No one said that build 130 would fix this issue.

**Comment by stevekr3w** [comment]
@MattBDev bro, first thanks for your answer, don't feel offended.
just wanna #bump (1month+ on priority) that cause it should be the first thing on the list and need to be fixed asap.
Anyway i appreciate all the work you guys do for a free-tool. ;)

**Comment by MattBDev** [comment]
It's a work in progress. The bug is really difficult to figure out. Since we are still figuring out how to solve this we don't want to stop everything else we are working on just to fix this one bug despite how bad it is.
Unfortunately IronApollo and I both work at supermarkets and the coronavirus came out of nowhere for us. We are both working some long hours right now.
I'm hoping some of what I am working on right now will make this issue a lot easier to fix.
(LOL. Github mobile has a big bug with quote replies right now. I hope I fixed your original comment)
