### ISSUE TITLE
//fixlighting .getSkyLight bug

### ISSUE THREAD

**Issue by KourisBP** [IntellectualSites/FastAsyncWorldEdit#496]
[config.txt](https://github.com/IntellectualSites/FastAsyncWorldEdit/files/4708179/config.txt)

# Bug report for FastAsyncWorldEdit 1.15.2

**[REQUIRED] FastAsyncWorldEdit Configuration Files:** 

**[REQUIRED] FastAsyncWorldEdit Version Number:** 

FastAsyncWorldEdit-1.15-256.jar
**[REQUIRED] Spigot/Paper Version Number:** 

paper-331.jar
**[REQUIRED] Description of the problem:**

When trying to do //fixlighting it throws out this error log
https://pastebin.com/bXMBkiaq
**How to replicate**:

//fixlighting in a dark area did it for me.
**Plugins being used on the server:**

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.15.2](https://ci.athion.net/job/FastAsyncWorldEdit-1.15/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by LoXR** [comment]
Can confirm aswell: https://mcpaste.io/f9e451e94e238188

**Comment by taooceros** [comment]
Same Bug, when there is a large area of block in high y-value, the bug will appear.

**Comment by Nightwielder1** [comment]
I'm also getting this issue with paper, but not restricted by the y-value. This appears to be the same bug as: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/510

**Comment by SecretlyJealous** [comment]
> Same Bug, when there is a large area of block in high y-value, the bug will appear.

> I'm also getting this issue with paper, but not restricted by the y-value. This appears to be the same bug as: #510

I think all these bugs are because of: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/497, doing any copy / paste above the 3rd chunk section from ground level in a plotworld in a brand new area for example will cause the build to be covered by shadows that cannot be fixed via command. You will have to restart the server and then run the command to fixlighting. I think it has something to do with the light engine getting stuck for some reason and if you unload and load the area again you will see differing results, it will also cause some neighboring chunk sections you didn't even touch to have shadows on them.
