### ISSUE TITLE
//snow and //thaw don't update the grass block

### ISSUE THREAD

**Issue by RedstoneFuture** [IntellectualSites/FastAsyncWorldEdit#557]
**[REQUIRED] FastAsyncWorldEdit Version Number:** 
1.16-306

**[REQUIRED] Spigot/Paper Version Number:** 
PaperMC 1.15.2-380

**[REQUIRED] Description of the problem:**

Without a blockupdate or a change of the block data "snowy" the texture of a grass_block are still wrong at the side or at the top.

So the command "//snow" have to set and "//thaw" have to remove this "snowy" flag.

![2020-07-29_13 52 22](https://user-images.githubusercontent.com/4140635/88798678-92261600-d1a5-11ea-8c62-e0d09d16858c.png)

Block 1 and 4 are right. But currently, with "//snow" I get block 2 and with "//thaw" I get block 3 if I use it over a grass_block.

**How to replicate**:

a location with a grass land:
1. "//snow 10"
2. "//thaw 10"

**Plugins being used on the server:**
-

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.1](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by MattBDev** [comment]
I'll provide a quick explanation for anyone that wants to fix this.
The grass blocks don't update because when we set blocks we bypass all physics and random tick updates. If I remember correctly we are replacing the entire ChunkSection where blocks are being changed. There are a few ways to trigger the update after the fact such as adding a Boolean parameter to one of the setting block methods or a new method that runs during the thaw operation.

**Comment by RedstoneFuture** [comment]
wtf?
