### ISSUE TITLE
Limits seem to bug out after certain amounts

### ISSUE THREAD

**Issue by Skizzles** [IntellectualSites/FastAsyncWorldEdit#762]
**[REQUIRED] FastAsyncWorldEdit Configuration Files** 

**/fawe debugpaste**:
https://haste.athion.net/rixafudava.coffeescript
https://haste.athion.net/uzalumuwez.bash

Latest logs contain too many ips etc to remove. Screenshot of logs when commands ran:
https://gyazo.com/1865ea028651c7a418aa10da99388b81

**Required Information**
- FAWE Version Number (`/version FastAsyncWorldEdit`):     Build 444
- Spigot/Paper Version Number (`/version`):     Paper(231) 1.16.3-R0.1-Snapshot
- Minecraft Version: [e.g. 1.16.4]     1.16.3

**Describe the bug**
Limits do not paste blocks above a certain amount, we have default limits set to 100 and these will not paste above like 35ish
[https://youtu.be/-NTM0OLyQaU](url)
**To Reproduce**
- Enable Limits
- Set limit to 100
- Add permission to user
- Attempt to world edit

**Plugins being used on the server**

https://screenshots.skizzles.me/wAnA3/PUrEriLI76.png
**Checklist**:

- [x] I included all information required in the sections above
- [x] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/FastAsyncWorldEdit/issues?q=is%3Aissue)
- [x] I made sure I am using an up-to-date version of [FastAsyncWorldEdit for 1.16.4](https://ci.athion.net/job/FastAsyncWorldEdit-1.16/)
- [x] I made sure the bug/error is not caused by any other plugin

**Comment by dordsor21** [comment]
Is this still an issue on the latest versions?

**Comment by Skizzles** [comment]
@dordsor21 yes, just tested and still occurring

**Comment by scottyboii** [comment]
Seems like we may be having the same issue..

Having an issue where players are unable to worldedit the correct amount of blocks..
Our limit on players is 2.5k blocks, and anything over that correctly warns that 
"Your WorldEdit operation was cancelled: Too many blocks changed"

However, selections that appear to be between 1.2k or so and 2.5k just don't do anything, and dont give any message in chat or error in console.

Then some selections around 1k only do parts of the actions.

Anything below 1k seems to work roughly fine.

Fawe - 581 
Paper - 1.16.5 (445)

https://athion.net/ISPaster/paste/view/e636787724ee4d5fb2ce4074899ed8ba

**Comment by scottyboii** [comment]
> Is this still an issue on the latest versions?
@dordsor21 

Still happening on latest, any updates?

https://athion.net/ISPaster/paste/view/61f1dc82b58c4b4a9f4fd6e489cc1d81

**Comment by hayhany** [comment]
I have had this problem too!

**Comment by Skizzles** [comment]
Still happening on latest build

**Comment by Skizzles** [comment]
https://www.youtube.com/watch?v=hJSxaONi_3k

**Comment by haloflooder** [comment]
So, if you set the worldedit block change limit to 1000 and you try to set lets say 3000 blocks. It'll change 1000 blocks but then get cancelled for "too many blocks changed". Instead of doing nothing like expected, it would set the 1000 blocks but you can't use //undo to roll it back. But changing anywhere between 1-1000 blocks works like normal.

![Issue demostration](https://i.imgur.com/6vQO8UG.gif)

Looking at the code for the limit extent (<https://github.com/IntellectualSites/FastAsyncWorldEdit/blob/main/worldedit-core/src/main/java/com/boydti/fawe/beta/implementation/processors/LimitExtent.java>), shouldn't it use `WEManager.IMP.cancelEditSafe` when it's cancelling a worldedit task? As a test, I created a custom extent and use the `cancelEditSafe` method after 500 blocks gets changed but it doesn't actually set the blocks when it cancels it.

![Custom extent demostration](https://i.imgur.com/UV7CKAK.gif)
