### ISSUE TITLE
No

### ISSUE THREAD

**Issue by AnonOPsUK** [IntellectualSites/FastAsyncWorldEdit#953]
### Server Implementation

Spigot

### Server Version

1.16.5

### Describe the bug

Every Spigot server (ALL VERSIONS) with FAWE (ALL VERSIONS) can be crashed with the following commands (no permissions needed):

/to for(i=0;i<256;i++){for(j=0;j<256;j++){for(k=0;k<256;k++){for(l=0;l<256;l++){ln(pi)}}}}
/targetoffset for(i=0;i<256;i++){for(j=0;j<256;j++){for(k=0;k<256;k++){for(l=0;l<256;l++){ln(pi)}}}}

Need to be fixed very quickly, because it can be used for crashing most servers !!

### To Reproduce

Type

/to for(i=0;i<256;i++){for(j=0;j<256;j++){for(k=0;k<256;k++){for(l=0;l<256;l++){ln(pi)}}}}
/targetoffset for(i=0;i<256;i++){for(j=0;j<256;j++){for(k=0;k<256;k++){for(l=0;l<256;l++){ln(pi)}}}}

and press ENTER or TAB it.

### Expected behaviour

Users without permissions to this command can't run this.

### Fawe Debugpaste

all versions

### Fawe Version

all versions

**Comment by AnonOPsUK** [comment]
Why it's Invalid?

**Comment by NotMyFault** [comment]
> Every Spigot server (ALL VERSIONS) with FAWE (ALL VERSIONS) can be crashed with the following commands (no permissions needed):

This is bluntly false. The named issue does not occur on modern, supported versions. It may occur on outdated, unsupported versions, but when using outdated versions you agree no support will be given.

**Comment by AnonOPsUK** [comment]
We have tested it from 1.8.8 to 1.16.5 after the 1.12.2 server of a friend was crashed with this bug. - On all it have  worked...

**Comment by LaurenceBarnes** [comment]
Then if it worked, why did you not put a debugpaste or a log from the crash on a 1.16.5 paper server with the most recent FAWE build in your report?

**Comment by AnonOPsUK** [comment]
Because it don't show some more infos. - It only let the server freeze...

**Comment by LaurenceBarnes** [comment]
What prevents you from retrieving logs from the logs folder when the server is stopped (after it freezed/crashed)?

**Comment by NotMyFault** [comment]
If someone can provide some more insight on modern & supported versions, we can look into it if we have the time to _if_ the issue is still present. 
Currently I am not able to reproduce the issue locally on Paper 1.16.5 526 and Fawe 1.16-616;99ea64f with and without the targetoffset permission; neither tab completing the input you've shown nor actually running it does anything.
![](https://i.imgur.com/ldZtqRY.png)
Until then, the issue will remain closed.

**Comment by AnonOPsUK** [comment]
I don't like to discus about it all the day, now the first people have tried it out too, I hope it get fixed before many servers going offline. - I have it reported, my job is done with that. - Look at this: [https://www.youtube.com/watch?v=0Gsmz462NbA](url)

I'm out. ;)

**Comment by NotMyFault** [comment]
> I don't like to discuss about it all the day, now the first people have tried it out too, I hope it get fixed before many servers going offline. - I have it reported, my job is done with that. - Look at this: [https://www.youtube.com/watch?v=0Gsmz462NbA](url)
> 
> I'm out. ;)

https://youtu.be/0Gsmz462NbA?t=466, ![](https://i.imgur.com/GauRtRF.png)
Nothing more to add.

**Comment by AnonOPsUK** [comment]
I can't understand what the problem is to fix it for all previos versions? - It is a huge bug and many kids are not able to fix it, it exist enought users wich prefer versions like 1.8 (for PVP) or 1.12 (because it need less server perfomance)...

**Comment by LaurenceBarnes** [comment]
The vast majority at this point is at 1.15 or 1.16. Older versions are unsafe and insecure, that is nothing new. The server devs do not support their old software as well. Use it at your own risk.

**Comment by NotMyFault** [comment]
> I can't understand what the problem is to fix it for all previous versions?

Time, lack of interest, and a variety of other things I could append here. Generally, we only support modern versions, like any other important software provider does, see Paper or Spigot for example. If a new version is released, the folks work very hard on publishing the next major release while dropping the current in the same run.
Maintaining versions back to 1.8 or even earlier is not what we are aiming for. If you choose to run outdated software, than you automatically admit you are on your own. If you choose to run an 1.8 server, you should have the knowledge to cover issues of all kinds in house, because you (most likely) know nobody supports that version (willingly [for free]) anymore.

The former author of FAWE for versions prior to 1.12 has deleted his GitHub profile including all his repositories and the main FAWE one. However, I transferred my fork to the organization if anyone is still willing to provide pull requests to fix issues. Since nobody has risen such a pull request in years, there is either no demand to see such an issue fixed or issues of that kind are fixed in house, like outlined previously.
If you are unable to fix those issues on your own, you definitely should not running unsupported software.
Better stick to something supported and you have a chance someone is actually willing to look into the issue.
